# Generated by Django 3.0.1 on 2024-08-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_phone_number',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
