# Generated by Django 3.0.1 on 2024-05-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0003_auto_20240511_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='size_option',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=80),
        ),
    ]
