# Generated by Django 3.0.1 on 2024-07-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='grand_total',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='default=0', editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
